config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"
  get "sessions/new"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users do
    resources :phone_numbers do
      resources :messages
    end
  end
  resources :account_activations, only: [:edit]
  resources :phone_number_verifications, only: [:new, :update]
end

app/controllers/phone_number_verifications_controller.rb
class PhoneNumberVerificationsController < ApplicationController
  before_action { @phone_number = PhoneNumber.find_by(id: params[:id]) }

  def new
  end

  def update
    if PhoneNumber.digest(params[:code]) == @phone_number.verification_digest
      @phone_number.toggle!(:verified)
      flash[:success] = "Phone Number Verified"
      redirect_to user_phone_number_path(current_user, @phone_number)
    else
      flash[:danger] = "Code entered is invalid"
      render 'new', status: :see_other
    end 
  end
end

app/helpers/phone_number_verifications_helper.rb
module PhoneNumberVerificationsHelper
end

app/views/phone_number_verifications/new.html.erb
<h3>Phone Number Verification</h3>
<%= form_with(url: phone_number_verification_path(@phone_number.id), method: "patch") do |f| %>
  <div class="container my-3">
    <div class="row align-items-start">
      <div class="col-sm-2">
        <%= f.label :code, "Enter code:" %>
      </div>
      <div class="col-sm-4 mb-4">
        <%= f.text_field :code, class: "form-control" %>
      </div>
      <div>
        <%= f.submit "Submit", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>