config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"
  get "sessions/new"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users do
    resources :phone_numbers do
      resources :messages
    end
  end
  resources :account_activations, only: [:edit]
  resources :phone_number_verifications, only: [:new, :update]
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token
  before_save :downcase_email
  before_create :create_activation_digest
  validates :name, presence: true, length: { maximum: 50 }
  has_many :phone_numbers, dependent: :destroy

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: true

  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }, allow_nil: true

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
    remember_digest
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
    BCrypt::Engine.cost
    password = BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  def session_token
    remember_digest || remember
  end

  def downcase_email
    self.email = email.downcase
  end

  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end

  def activate
    update_attribute(:activated, true)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorized_user, only: [:show, :edit, :update, :destroy]

  def index
    unless current_user.admin?
      flash[:danger] = "You are not authorized to view this page"
      redirect_to current_user
    end
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    add_breadcrumb(@user.name, @user)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email for the link to activate your account"
      redirect_to root_url
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to login_path, status: :see_other
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def authorized_user
      if logged_in?
        @user = User.find_by(id: params[:id])
        unless !!@user && @user == current_user
          flash[:danger] = "You are not authorized to view the requested page"
          redirect_to current_user
        end
      else
        flash[:danger] = "You must log in to view the requested page"
        redirect_to login_path
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<tr>
  <th scope="row"><%= user.id %></th>
  <td><%= user.email %></td>
  <td><%= user.name %></td>
  <td><%= user.activation_digest %></td>
  <td><%= link_to "Delete", user, data: { "turbo-method": :delete,
  turbo_confirm: "You sure?" } %></td>
</tr>

app/views/users/edit.html.erb
<div class="container px-5">
  <div class="h2 my-4">Edit your account</div>
  <%= form_with(model: @user) do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    <div class="row align-items-start">
      <%= f.label :name, "Name", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-4 mb-4">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>
    <div>
      <%= f.submit "Edit your account", class: "btn btn-primary" %>
    </div>
  <% end %>
  <p class="h6 my-4"><%= link_to "Delete your account", user_path(@user), data: { "turbo-method": :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger" %></p>
</div>

app/views/users/index.html.erb
<h1>All Users</h1>
<div>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">User id</th>
        <th scope="col">Email</th>
        <th scope="col">Name</th>
        <th scope="col">Activation Digest</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
      <%= render @users %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<div class="container px-5">
  <div class="h2 my-4">Create your account</div>
  <%= form_with(model: @user) do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    <div class="row align-items-start">
      <%= f.label :name, "Name", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-4 mb-4">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>
    <div class="row align-items-start">
      <%= f.label :email, "Email", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-4 mb-4">
        <%= f.email_field :email, class: "form-control" %>
      </div>
    </div>
    <div class="row align-items-start">
      <%= f.label :password, "Password", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-4 mb-4">
        <%= f.password_field :password, class: "form-control" %>
      </div>
    </div>
    <div class="row align-items-start">
      <%= f.label :password_confirmation, "Confirm", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-4 mb-4">
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
    </div>
    <div>
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    </div>
  <% end %>
  <p class="h6 my-4">Already have an account? <%= link_to "Log In", login_path %></p>
</div>

app/views/users/show.html.erb
<div class="container py-2">
  <div class="row">
    <div class="col">
      <div class="h3">My Phone Numbers</div>
    </div>
    <div class="col text-end">
      <%= link_to "Add New Number", new_user_phone_number_path(@user), class: "btn btn-primary" %>
    </div>
  </div>
</div>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Number</th>
      <th scope="col">Verified</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    <%= render @user.phone_numbers %>
  </tbody>
</table>