config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"
  get "sessions/new"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users do
    resources :phone_numbers do
      resources :messages
    end
  end
  resources :account_activations, only: [:edit]
  resources :phone_number_verifications, only: [:new, :update]
end

app/models/phone_number.rb
class PhoneNumber < ApplicationRecord
  attr_accessor :verification_code
  before_validation :format_number, on: :create
  before_create :create_verification_digest

  belongs_to :user
  has_many :messages, dependent: :destroy

  VALID_PHONE_NUMBER_REGEX = /\A\+1[0-9]{10}\z/
  validates :number, presence: true, uniqueness: true,
                     format: { with: VALID_PHONE_NUMBER_REGEX }

  def PhoneNumber.new_verification_code
    code = 6.times.map{rand(10)}.join
    puts "code: #{code}"
    code
  end

  def PhoneNumber.digest(code)
    Digest::SHA256.hexdigest(code)
  end

  def create_verification_digest
    self.verification_code = PhoneNumber.new_verification_code
    self.verification_digest = PhoneNumber.digest(verification_code)
  end

  def send_verification_text
    client = Twilio::REST::Client.new
    client.messages.create(
      from: ENV['TWILIO_FROM_NUMBER'],
      body: "Hello! Your TextMyPhone verification code is #{verification_code}",
      to: number
    )
  end

  def send_sms(body)
    client = Twilio::REST::Client.new
    client.messages.create(
      from: ENV['TWILIO_FROM_NUMBER'],
      body: body,
      to: number
    )
  end

  def verify
    toggle!(:verified)
  end

  def format_number
    self.number = number.gsub(/\D/, '').prepend('+1')
  end
end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController
  before_action :authorized_user
  def new
    @phone_number = @user.phone_numbers.build
    add_breadcrumb "Add New Number"
  end

  def create
    @phone_number = @user.phone_numbers.build(phone_number_params)
    if @phone_number.save
      @phone_number.send_verification_text if ENV['RAILS_ENV'] == 'production'
      flash[:success] = "You will receive a verification code via SMS message. Please enter it here."
      redirect_to new_phone_number_verification_path(id: @phone_number.reload.id)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def show
    if @phone_number = @user.phone_numbers.find_by(id: params[:id])
      add_breadcrumb(@phone_number.number)
      @messages = @phone_number.messages
    else
      flash[:warning] = "Either this phone number does not exist or you are not authorized to view it."
      redirect_to @user
    end
  end

  def destroy
    if @phone_number = @user.phone_numbers.find_by(id: params[:id])
      @phone_number.destroy
      redirect_to @user, status: :see_other
    else
      flash[:warning] = "Either this phone number does not exist or you are not authorized to view it."
      redirect_to @user
    end
  end

  private

    def phone_number_params
      params.require(:phone_number).permit(:number)
    end

    def authorized_user
      if logged_in?
        @user = User.find_by(id: params[:user_id])
        add_breadcrumb(@user.name, user_path(@user))
        unless !!@user && @user == current_user
          flash[:danger] = "You are not authorized to view the requested page"
          redirect_to current_user
        end
      else
        flash[:danger] = "You must log in to view the requested page"
        redirect_to login_path
      end
    end
end

app/helpers/phone_numbers_helper.rb
module PhoneNumbersHelper
end

app/views/phone_numbers/_phone_number.html.erb
<tr>
  <th scope="row"><%= link_to phone_number.number, user_phone_number_path(@user, phone_number) %></th>
  <td><%= phone_number.verified? ? bootstrap_icon("check", width: 20, height: 20, fill: "green") : bootstrap_icon("x", width: 20, height: 20, fill: "red")%></td>
  <td><%= link_to "Delete", user_phone_number_path(@user, phone_number), data: { "turbo-method": :delete,
  turbo_confirm: "Are you sure? You will lose all messages associated with this number." } %></td>
</tr>

app/views/phone_numbers/new.html.erb
<h3>Enter a valid 10-digit US or Canadian phone number.</h3>
<%= form_with model: [@user, @phone_number] do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="container my-3">
    <div class="row align-items-start">
      <div class="col-sm-2">
        <%= f.label :number, "Number", class: "col-form-label" %>
      </div>
      <div class="col-sm-4 mb-4">
        <%= f.telephone_field :number, class: "form-control", value: @phone_number.number ? @phone_number.number.gsub(/\+1/, '') : '' %>
      </div>
    </div>
    <div>
      <%= f.submit "Add Phone Number", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/phone_numbers/show.html.erb
<div class="container py-2">
  <div class="row">
    <div class="col">
      <div class="h3">Messages</div>
    </div>
    <div class="col text-end">
      <% if @phone_number.verified? %>
        <%= link_to "Send new message", new_user_phone_number_message_path(@user, @phone_number), class: "btn btn-primary" %>
      <% else %>
        <%= link_to "Verify this number", new_phone_number_verification_path(id: @phone_number.id), class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Message id</th>
      <th scope="col">Body</th>
    </tr>
  </thead>
  <tbody>
    <%= render @phone_number.messages %>
  </tbody>
</table>