config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"
  get "sessions/new"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users do
    resources :phone_numbers do
      resources :messages
    end
  end
  resources :account_activations, only: [:edit]
  resources :phone_number_verifications, only: [:new, :update]
end

app/views/layouts/_breadcrumb.html.erb
<li class='breadcrumb-item'><%= link_to breadcrumb.name, breadcrumb.path %></li>

app/views/layouts/_breadcrumbs_bar.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <%= render breadcrumbs %>
  </ol>
</nav>

app/views/layouts/_flash_alerts.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand h1 bg-primary bg-gradient text-white p-2 mt-1" href=<%= root_path %>>TextMyPhone</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0"> 
          <% if logged_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                My Account
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><%= link_to "My Phone Numbers", @user, class: "dropdown-item" %></li>
                <li><%= link_to "Edit My Account", edit_user_path(@user), class: "dropdown-item" %></li>
                <% if current_user.admin? %>
                  <li><%= link_to "All Users", users_path, class: "dropdown-item" %></li>
                <% end %>
                <li><hr class="dropdown-divider"></li>
                <li><%= link_to "Log Out", logout_path, class: "dropdown-item", data: { "turbo-method": :delete } %></li>
              </ul>
            </li>                
          <% else %>
            <li class="nav-item">
              <%= link_to "Log In", login_path, class: "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to "About", "#", class: "nav-link" %>
          </li>
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TextMyPhone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="container my-4">
    <header>
      <%= render "layouts/navbar" %>
      <%= render "layouts/flash_alerts" %>
      <%= render "layouts/breadcrumbs_bar" %>
    </header>
    <main class="container">
      <%= yield %>
    </main>
    <div>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>